name: Generate GitHub Profile Stats

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Create Profile Folder
        run: |
          mkdir -p profile
          echo "Profile folder created"

      - name: Generate GitHub Stats
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            --retry 5 \
            --retry-all-errors \
            --retry-delay 3 \
            "https://github-readme-stats.vercel.app/api?username=nawsintabassum&show_icons=true&theme=tokyonight&hide_border=true" \
            -o profile/stats.svg

      - name: Generate Top Languages
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            --retry 5 \
            --retry-all-errors \
            --retry-delay 3 \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=nawsintabassum&layout=compact&theme=tokyonight&hide_border=true&langs_count=8" \
            -o profile/top-langs.svg

      - name: Generate Activity Graph
        run: |
          curl -L \
            -A "Mozilla/5.0" \
            --retry 5 \
            --retry-all-errors \
            --retry-delay 3 \
            "https://github-readme-activity-graph.vercel.app/graph?username=nawsintabassum&theme=tokyo-night&hide_border=true&area=true" \
            -o profile/activity-graph.svg

      - name: Check Generated Files
        run: |
          echo "Checking profile folder:"
          ls -la profile/

      - name: Commit and Push Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/

          git status

          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Update profile statistics"
            git push origin HEAD:main
          fi
